### ISSUE TITLE
Audio-only Android support

### ISSUE THREAD

**Issue by mohsindlb** [DolbyIO/comms-sdk-unreal#238]
Currently unreal sdk does not support android OS. 

Can you please provide the support on android.

**Comment by psih369** [comment]
Audio-only support for iOS would be great too. 
Looking forward to have Quest Pro (android VR) and iPad (iOS) XR experience with voice chat from external users.

**Comment by malcriado3d** [comment]
By any chance, is there any news about a tentative date for Android feature? Thanks in advance!

**Comment by kubaau** [comment]
@malcriado3d Sorry about the delay, I was on holiday. I believe there has been significant progress made in the plugin's underlying component so this feature may come fairly soon, but I haven't had the time to check @codlab 's work yet. Maybe he can say more :)

**Comment by malcriado3d** [comment]
is there any news on support for Android devices? thanks in advance!

**Comment by psih369** [comment]
Are there any timeline updates for the Android support? The big project is coming in October, and we would love to have Dolby comms integration.

**Comment by codlab** [comment]
We currently have 3 remaining facing issues that are not specifically about unreal but the overall layer underneath it. Those are about early spatialisation, audio device selection beside a last one a bit more important in term of work which is video related (sender side). I'm confident we can have those first 2 by the end of august - for the video, it'll be a bit more work (but at least without any crashes by that time as well) 👀

**Comment by codlab** [comment]
Hhhmmm it's a bit of uncharted territory but I'll try to push something forward either way 🤔 (beside sending video as this one is definitely an unknown on my side, can't commit to a clear timeline rn !)

**Comment by GaryMakinDolby** [comment]
> Thank you for your quick answer!
> Is it possible to have some early tests running (even if it is crashing)? Our client (Porsche) is heavily invested in the project and we would love to prepare all the necessary implementation (like voice chat ui) ready on our side.

phih369, I am the product manager at Dolby for the plugin. I would like to talk with you about your project, and to see how we can assist you further. If you are interested, please contact me at gary.makin with a domain name of dolby.com.

**Comment by kubaau** [comment]
Version 1.2.0 contains an experimental plugin build for Android. It supports arm64-v8a devices and UE5.3 only. Please see this [tutorial](https://api-references.dolby.io/comms-sdk-unreal/docs/tutorial/android) for how to use it. Since the Android version is based on a different [C++ SDK](https://github.com/DolbyIO/comms-sdk-cpp) which has not been released, it may require some additional "ifdefing" to make both a desktop and an Android version work at the same time. The plugin can work on an older UE5 but it would require [additional configuration](https://github.com/DolbyIO/comms-sdk-unreal/commit/3963494789bc548166bdb3ed853014d08bff1ea4). This project will not longer be maintained so this experimental build is the best we can do right now.
