### ISSUE TITLE
Documentation for release and beta versions

### ISSUE THREAD

**Issue by GaryMakinDolby** [DolbyIO/comms-sdk-unreal#355]
There is only one set of documentation pages, and these are updated for the latest beta version.

However, these pages may then reference features that are not available in the current GA version.

Is it possible to have two sets of documentation hosted on GitHub?

**Comment by kubaau** [comment]
I think how this can be accomplished is more of a question towards @FabienLavocat and @mhelf-dolby . It would be ideal to have separate documentation for each tag. Then it would be possible to have the default documentation be for the latest release (not beta) and a combobox selector for all tagged versions (including betas).

**Comment by mhelf-dolby** [comment]
Docusaurus supports [versioning](https://docusaurus.io/docs/versioning), although they have this warning in their documentation: "Most of the time, you don't need versioning as it will just increase your build time, and introduce complexity to your codebase.". So I'm not sure if this is the best solution, but we may test it. WDYT?

**Comment by FabienLavocat** [comment]
That will make things really complex I think to use the versioning from Docusaurus. What about adding a Beta tag in the doc for features that are not GA yet?

**Comment by GaryMakinDolby** [comment]
At the moment, the tutorials do not all work for the release version but some of those could be tagged as beta. Where the tag cannot work is when something has changed.

**Comment by mhelf-dolby** [comment]
I agree, this is probably the best idea. I'll add the tags.

**Comment by mhelf-dolby** [comment]
@GaryMakinDolby please take a look at the documentation and let me know whether the beta tags that we currently have are sufficient.

**Comment by kubaau** [comment]
There's still some work to be done on tutorials I think:
- https://api-references.dolby.io/comms-sdk-unreal/docs/tutorial/first-conference#option-b---use-authentication-url this is beta
- These are at least slightly different in beta due to folder and widget cleanup:
  - https://api-references.dolby.io/comms-sdk-unreal/docs/tutorial/camera-preview
  - https://api-references.dolby.io/comms-sdk-unreal/docs/tutorial/remote-video
  - https://api-references.dolby.io/comms-sdk-unreal/docs/tutorial/screenshare-preview
  - https://api-references.dolby.io/comms-sdk-unreal/docs/tutorial/remote-screenshare
  - https://api-references.dolby.io/comms-sdk-unreal/docs/tutorial/device-management
I'm not really sure how to best address this last point without versioning.

**Comment by kubaau** [comment]
I think now the issue can be closed once @GaryMakinDolby approves it.

**Comment by kubaau** [comment]
Closing, please reopen if necessary.
