### ISSUE TITLE
Screen Sharing Race Condition Crash (UE5.2)

### ISSUE THREAD

**Issue by RFCOSOCIETY** [DolbyIO/comms-sdk-unreal#393]
**Describe the bug**

Sometimes when screen sharing, utilizing the texture provided by the Dolby SDK as brush for an UImage, will result in a crash.
We believe it is due to a race condition.

![MicrosoftTeams-image](https://github.com/DolbyIO/comms-sdk-unreal/assets/127212080/503dbd24-a12b-47a6-b75f-82cdd1eaadb2)

**Expected Behavior**

To not crash while screen sharing.

**Minimalistic code (recommended)**

![image](https://github.com/DolbyIO/comms-sdk-unreal/assets/127212080/27634c59-4170-482e-a89e-bfaa9d6c6b17)

**Specifications**

-   Windows 10/11
-   Version:
    -   1.1.6

**Comment by kubaau** [comment]
@RFCOSOCIETY 

This is probably an easy fix, but I am curious about this because it logically should not happen. Based on "line 219" in the call stack I assume this is with regards to receiving screen share (as opposed to sharing your screen). I would appreciate some logs, preferably from both the Output Log and the ones obtained by using the [`Set Log Settings`](https://api-references.dolby.io/comms-sdk-unreal/docs/blueprints/functions#dolbyio-set-log-settings) function. It looks like a `remote_video_track_removed` event is received before or at the same time as a `remote_video_track_added` event. I have never seen this so I didn't think any special attention was necessary with regards to this TMap. What is the reproduction rate for this? I may have trouble making 100% sure this is fixed if I cannot reproduce it.

@djova-dolby FYI for now

**Comment by AntonIovbakDev** [comment]
[cppsdk-2023-09-12-08-30-11.log](https://github.com/DolbyIO/comms-sdk-unreal/files/12583422/cppsdk-2023-09-12-08-30-11.log)

**Comment by AntonIovbakDev** [comment]
Hi guys! Additional information. While trying to reproduce crash we made these steps:

1. One user shared his screen
2. Other users saw translation
3. During the translation user closed an app with alt-F4
4. A couple of the users, who saw the translation had a crash.

This time we have the similar call stack as in a first screenshot here, and the log I've sent.

Hope this could help somehow

**Comment by kubaau** [comment]
The protection against this kind of race should be improved in 1.1.7 and 1.2.0-beta.11.

**Comment by AntonIovbakDev** [comment]
We will use 1.2 beta then. Thnx for your answers
