### ISSUE TITLE
Calling disconnect within screen sharing causes error

### ISSUE THREAD

**Issue by AntonIovbakDev** [DolbyIO/comms-sdk-unreal#406]
**Describe the bug**

If user close UE app during a screensharing, error appears. Disconnect method called for dolby plugin within shutdown the UE5 app, `exit` or alt-F4, both cause the error

**Expected Behavior**

Don't have any errors by closing app.

**Specifications**

-   OS: windows 10
-   Version:
    - UE5 v5.2.1
    - dolby v1.1.6
![Screenshot_42](https://github.com/DolbyIO/comms-sdk-unreal/assets/144774935/7f26fecd-8782-4089-b49c-7a410d695fcc)
[cppsdk-2023-09-13-15-59-09.log](https://github.com/DolbyIO/comms-sdk-unreal/files/12598380/cppsdk-2023-09-13-15-59-09.log)

Now we are using hotfix just like that, but maybe it is not a proper way to handle it:

![image](https://github.com/DolbyIO/comms-sdk-unreal/assets/144774935/fee55fa9-e51c-4951-8d2a-6fc9db4432dd)

**Comment by kubaau** [comment]
@AntonIovbakDev This is probably similar to #374 which was fixed with https://github.com/DolbyIO/comms-sdk-unreal/pull/375/commits/dc048a1d849887d4c6210a25d59a87064c214aba . It looks likely that 1.2.0 will never come out of beta and I may be unable to release a patch for 1.1. I suggest using the main branch of this repository instead of the releases in that case.

**Comment by kubaau** [comment]
I ported that patch and released version [1.1.8](https://github.com/DolbyIO/comms-sdk-unreal/releases/tag/1.1.8). I am not sure if this fixes this exact issue, but the project will no longer be maintained so this is the best I can do now. Regardless, I recommend using version [1.2.0](https://github.com/DolbyIO/comms-sdk-unreal/releases/tag/1.2.0) instead.
