### ISSUE TITLE
The zip file does not contain a DolbyIO directory

### ISSUE THREAD

**Issue by adamallaf** [DolbyIO/comms-sdk-unreal#44]
There is no DolbyIO directory containing the plugin in the zip file and instead the directories/files are in the zip's root, which requires the user to create `DolbyIO/` directory inside `Plugins/` and then extract the zip to `Plugins/DolbyIO/`.

![image](https://user-images.githubusercontent.com/5655997/214308312-a50db4de-759b-4d69-a349-a2cc807681cf.png)

**Comment by kubaau** [comment]
This is not 100% accurate but is also valid. You don't need the folder to be named DolbyIO. The readme is purposely vague about this because we know zipping to be an issue: #34.

I can propose a short-term solutions and a long-term one:
- (short) make it clear in readme to extract to folder named such-and-such
- (long) change the way we create the zips - this has already proven a problem and would require further investigation @msobo1

**Comment by kubaau** [comment]
@adamallaf Could you coordinate with @mhelf-dolby how you would like the readme to be reworded?

**Comment by kubaau** [comment]
@adamallaf 👆🏻

**Comment by kubaau** [comment]
I checked the 1.1.0-beta.6 releases and they seem to be packaged as expected.
